artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  source_URL: https://github.com/ArihantSingla21/datasets-/raw/main/summarizer-data.zip
  local_data_file : artifacts/data_inegstion/data.zip
  unzip_dir : artifacts/data_ingestion
